#include "ParallelRadixSort.cuh"

//// Integral Types
//DEFINE_RADIX_VALUE_BOTH(int)
//DEFINE_RADIX_VALUE_BOTH(unsigned int)
//DEFINE_RADIX_VALUE_BOTH(float)
//DEFINE_RADIX_VALUE_BOTH(double)
//DEFINE_RADIX_VALUE_BOTH(int64_t)
//DEFINE_RADIX_VALUE_BOTH(uint64_t)
//
//// ID type sorting
//DEFINE_RADIX_KEY_VALUE_ALL(int)
//DEFINE_RADIX_KEY_VALUE_ALL(unsigned int)
//DEFINE_RADIX_KEY_VALUE_ALL(int64_t)
//DEFINE_RADIX_KEY_VALUE_ALL(uint64_t)