#include "ParallelRadixSort.cuh"

// Integral Types
DEFINE_RADIX_VALUE_BOTH(int32_t)
DEFINE_RADIX_VALUE_BOTH(uint32_t)
DEFINE_RADIX_VALUE_BOTH(double)
DEFINE_RADIX_VALUE_BOTH(float)
DEFINE_RADIX_VALUE_BOTH(int64_t)
DEFINE_RADIX_VALUE_BOTH(uint64_t)

// ID type sorting
DEFINE_RADIX_KEY_VALUE_ALL(int32_t)
DEFINE_RADIX_KEY_VALUE_ALL(uint32_t)
DEFINE_RADIX_KEY_VALUE_ALL(double)
DEFINE_RADIX_KEY_VALUE_ALL(float)
DEFINE_RADIX_KEY_VALUE_ALL(int64_t)
DEFINE_RADIX_KEY_VALUE_ALL(uint64_t)